export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT';
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAIL";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_POPUP_PRODUCT = "GET_POPUP_PRODUCT";
export const GET_PRODUCT_FILTERS = "GET_PRODUCT_FILTERS";

export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PURCHASE_PRODUCT = "PURCHASE_PRODUCT"
export const PURCHASE_ERROR = "PURCHASE_ERROR"
export const GET_PURCHASE = "GET_PURCHASE"
export const GET_PURCHASES = "GET_PURCHASES"

export const SET_CURRENT_FILTERS = "SET_CURRENT_FILTERS"